apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/port: '57729'
  creationTimestamp: null
  labels:
    app: hn-flask
  name: hn-flask
spec:
  ports:
  - name: web
    port: 57729
    protocol: TCP
    targetPort: 57729
  selector:
    app: hn-flask
  type: NodePort
