{
 "title": "API metrics Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total requests by status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_duration_seconds_count{path=\"/stories\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\"}[1m])) by (endpoint) / sum(rate(flask_http_request_duration_seconds_count{status=\"200\"}[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Response time per request",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "response_time", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}