apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pu
  name: pu
spec:
  containers:
  - image: 551955/flask_hackernews:hn-flask
    name: pu
    volumeMounts:
     - name: logs
       mountPath: /HN_top50/logs
    resources: {}
  volumes:
   - emptyDir: {}
     name: logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
